version: "3"
services:
  cassandra-1:
    container_name: cassandra-1
    image: cassandra:latest
    ports:
      - "9042:9042"
      - "7000"
    networks:
      - cassandra-network
    command: -Dcassandra.config=/home/cassandra.yaml
    healthcheck:
      test:
        [
          "CMD",
          "cqlsh",
          "-u cassandra",
          "-p cassandra",
          "-e describe keyspaces"
        ]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra-2:
    container_name: cassandra-2
    image: cassandra:latest
    ports:
      - "9043:9042"
      - "7002"
    networks:
      - cassandra-network
    command: -Dcassandra.config=/home/cassandra.yaml
    healthcheck:
      test:
        [
          "CMD",
          "cqlsh",
          "-u cassandra",
          "-p cassandra",
          "-e describe keyspaces"
        ]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra-3:
    container_name: cassandra-3
    image: cassandra:latest
    ports:
      - "9044:9042"
      - "7003"
    networks:
      - cassandra-network
    command: -Dcassandra.config=/home/cassandra.yaml
    healthcheck:
      test:
        [
          "CMD",
          "cqlsh",
          "-u cassandra",
          "-p cassandra",
          "-e describe keyspaces"
        ]
      interval: 15s
      timeout: 10s
      retries: 10

  nginx:
    container_name: nginx
    image: nginx-cassandra
    networks:
      - cassandra-network
    ports:
      - "80:80"
    depends_on:
      - cassandra-1
      - cassandra-2
      - cassandra-3

networks:
  cassandra-network:
    external: true
